return {
  branch = require("neogit.popups.branch"),
  cherry_pick = require("neogit.popups.cherry_pick"),
  commit = require("neogit.popups.commit"),
  diff = require("neogit.popups.diff"),
  fetch = require("neogit.popups.fetch"),
  help = require("neogit.popups.help"),
  -- ignore = require("neogit.popups.ignore"),
  log = require("neogit.popups.log"),
  -- merge = require("neogit.popups.merge"),
  pull = require("neogit.popups.pull"),
  push = require("neogit.popups.push"),
  rebase = require("neogit.popups.rebase"),
  remote = require("neogit.popups.remote"),
  reset = require("neogit.popups.reset"),
  -- revert = require("neogit.popups.revert"),
  stash = require("neogit.popups.stash"),
}
